707809188586:
    presets:
      - "aws-organizations"
      - "aws-service"
  894426806671:
    presets:
      - "aws-organizations"
      - "aws-service"
  285679047437:
    presets:
      - "aws-organizations"
      - "aws-service"
  885801475464:
    presets:
      - "aws-organizations"
      - "aws-service"
  714562008810:
    presets:
      - "aws-organizations"
      - "aws-service"
  992222228210:
    presets:
      - "aws-organizations"
      - "aws-service"
  203271543287:
    presets:
      - "aws-organizations"
      - "aws-service"
  564088821524:
    presets:
      - "aws-organizations"
      - "aws-service"
  424571028400:
    presets:
      - "aws-organizations"
      - "aws-service"
  693023368022:
    presets:
      - "aws-organizations"
      - "aws-service"
  962480255828:
    presets:
      - "aws-organizations"
      - "aws-service"
  686270819255:
    presets:
      - "aws-organizations"
      - "aws-service"
  284445534808:
    presets:
      - "aws-organizations"
      - "aws-service"
  501984417376:
    presets:
      - "aws-organizations"
      - "aws-service"
  477995668264:
    presets:
      - "aws-organizations"
      - "aws-service"
  595058326297:
    presets:
      - "aws-organizations"
      - "aws-service"
  484497069811:
    presets:
      - "aws-organizations"
      - "aws-service"
  137893875086:
    presets:
      - "aws-organizations"
      - "aws-service"
  486183534890:
    presets:
      - "aws-organizations"
      - "aws-service"
  957507561258:
    presets:
      - "aws-organizations"
      - "aws-service"
  870669727545:
    presets:
      - "aws-organizations"
      - "aws-service"
  126316686161:
    presets:
      - "aws-organizations"
      - "aws-service"
  969799237091:
    presets:
      - "aws-organizations"
      - "aws-service"
  518551558056:
    presets:
      - "aws-organizations"
      - "aws-service"
  575977136211:
    presets:
      - "aws-organizations"
      - "aws-service"
  131674823919:
    presets:
      - "aws-organizations"
      - "aws-service"
  276555828362:
    presets:
      - "aws-organizations"
      - "aws-service"
  678668390304:
    presets:
      - "aws-organizations"
      - "aws-service"
  296615500438:
    presets:
      - "aws-organizations"
      - "aws-service"
  472454369658:
    presets:
      - "aws-organizations"
      - "aws-service"
  925479565843:
    presets:
      - "aws-organizations"
      - "aws-service" 
  700778905650:
    presets:
      - "aws-organizations"
      - "aws-service"
  690456518676:
    presets:
      - "aws-organizations"
      - "aws-service"
  566844520118:
   presets:
     - "aws-organizations"
     - "aws-service"     
  844112306741:
    presets:
      - "aws-organizations"
      - "aws-service"      
  745854088131:
    presets:
      - "aws-organizations"
      - "aws-service"
  539158963566:
    presets:
      - "aws-organizations"
      - "aws-service" 
  441131366154:
    presets:
      - "aws-organizations"
      - "aws-service"
  159398445531:
    presets:
      - "aws-organizations"
      - "aws-service"
  813812644529:
    presets:
      - "aws-organizations"
      - "aws-service"
  
resource-types:
  excludes:
  - CodePipelinePipeline
  - CodeBuildProject
  - IAMRolePolicyAttachment
  - IAMRolePolicy
